### ISSUE TITLE
API for all reported posts and comments

### ISSUE THREAD

**Issue by Ang-YC** [Ang-YC/kidsbook-backend#35]
**Suggested endpoint:** `/group/<group_id>/flagged`
**Enhancement:** `/group/<group_id>/flagged?status=<status>` to filter only posts of certain status

Please understand the requirements clearly, **all flagged posts and comments**, try to sort it in order of time in ascending order.

---

**Minimum output:**
- user_id
- user_photo
- user_name
- post_id
- comment_id (Can be NULL if it is a report for post)
- status
- created_at

_(You can output the nested attribute such as `post_id` to **Post** object, if not I can do lazy loading)_

---

When you are done, copy paste the list above and fill in all the rows with the key that can access that information, example:

- user_id: `user.id`
- user_photo: `user.profile_photo`
...

**Comment by snguyenthanh** [comment]
I would suggest separating the comments and posts in the response. As if we use nested comments in the posts, we will need to filter out all unflagged comments in all posts.

The suggested format of the response would be:
```
{
    'data': {
        'posts': [...],
        'comments': [...]
    }
}
```

**Comment by Ang-YC** [comment]
You have a good point, this looks good but make sure `post_id` is present in comments.

Note that each post can be flagged by multiple people, all should be returned as individual report. This is because in the future we might add a input box that allow users to write why they reported them.
