### ISSUE TITLE
Notification feature

### ISSUE THREAD

**Issue by Ang-YC** [Ang-YC/kidsbook-backend#36]
Suggestion: Add 2 new table

# notification
- `id` *PK*
- `user_id` *FK*
- `group_id` *FK*
- `action_user_id` *FK* (User ID of the user that performed the action, such as like / comment)
- `content` *VARCHAR(512)* (Short content about the post, example: Ang YC liked on your post)
- `payload` *TEXT* (JSON that contains other information such as ID to the post)
- `timestamp` *DATETIME*

# notification_user
- `id` *PK*
- `user_id` *FK*
- `group_id` *FK*
- `last_seen` *DATETIME*

This will take long time to finish because have to decide which event to trigger notification on which user, think carefully on the logic

---

Suggested endpoint:
- `GET /group/<group_id>/notifications`
- `PUT /group/<group_id>/notifications`
  - `last_id`: last seen notification's id, get `timestamp` from `notification` table and update `last_seen` in `notification_user`

---

Minimum output:
- notifications
  - id
  - action_user_id
  - action_user_photo
  - action_user_name
  - content
  - payload
  - timestamp

---

When you are done, copy paste the list above and fill in all the rows with the key that can access that information

**Comment by snguyenthanh** [comment]
Can you please explain what `notification_user` is used for ?

**Comment by Ang-YC** [comment]
It is used to record when was the last notification the user had read on a specific group, to show the number of unread notifications. By the way, I have added a new field to allow push notification
