### ISSUE TITLE
Permission Issue

### ISSUE THREAD

**Issue by Ang-YC** [Ang-YC/kidsbook-backend#42]
Better way to implement permission:

## Multi-tenant Hierarchy

1. System
2. Organization (School)
3. Group (Class)

## User level

1. Admin
2. Headmaster / School IT team
3. Teacher
4. Student / Parent / Guest

---

But we have no time now, the above design required significant amount of changes in the database schema, so what can be fixed currently is the following (in short):

Superuser's permission on the system:

|  | View | Update | Add/remove to same group | Add to other groups |
|---|---|---|---|---|
| Superusers | ✅ | ❌ | ✅ | ❌ |
| Non-superusers in same group | ✅ | ✅ | ✅ | ❌ |
| Non-superusers in different group | ❌ | ❌ | ❌ | ❌ |
| Non-superusers created by that superuser | ✅ | ✅ | ✅ | ❌ |

*Superuser can only create non-superuser, superuser are created manually by us for now

---

The above design should be reflected in:
- `/user/`
- `/user/update/<user_id>`
- `/group/<group_id>/user/<user_id>/` (GET & POST)
- `/batch/create/user/<file_name>/`

Thus this can be deprecated:
- `/users/non_group/`

---

This permission will be changed a lot if this project is tested to be working

**Comment by snguyenthanh** [comment]
As `role=0` is reserved for Admin (need to add to the `Role` table), we can use it to allow/block create/update superusers.

**Comment by Ang-YC** [comment]
This is consider done for now, closing
